controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot_bazu_controller:
      type: position_controllers/JointGroupPositionController

robot_bazu_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity